<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="PB_TestRunner" Id="{79a7c997-fb55-4cc1-a800-4387fd6d2214}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PB_TestRunner
VAR
    Test_ReadBySymbolName                    : Test_ReadBySymbolName;
    Test_ReadWriteBySymbolName               : Test_ReadWriteBySymbolName;
    Test_WriteBySymbolName                   : Test_WriteBySymbolName;

    Test_ReadBySymbolName_KeepingHandle      : Test_ReadBySymbolName_KeepingHandle;
    Test_ReadWriteBySymbolName_KeepingHandle : Test_ReadWriteBySymbolName_KeepingHandle;
    Test_WriteBySymbolName_KeepingHandle     : Test_WriteBySymbolName_KeepingHandle;
    
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[tcl_UnitTest.TestFramework.TestRunner();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>